class MeleeCharacter
  def initialize(charNum)
    @charnum = charNum
  end

  def get_character
    case @charnum
    when "1.png"
      return "Bowser"
    when "2.png"
      return "Captain Falcon"
    when "3.png"
      return "Donkey Kong"
    when "4.png"
      return "Dr. Mario"
    when "5.png"
      return "Falco"
    when "6.png"
      return "Fox"
    when "7.png"
      return "Ganondorf"
    when "8.png"
      return "Ice Climbers"
    when "9.png"
      return "Jiggly Puff"
    when "10.png"
      return "Kirby"
    when "11.png"
      return "Link"
    when "12.png"
      return "Luigi"
    when "13.png"
      return "Mario"
    when "14.png"
      return "Marth"
    when "15.png"
      return "Mewtwo"
    when "16.png"
      return "Mr. Game & Watch"
    when "17.png"
      return "Ness"
    when "18.png"
      return "Peach"
    when "19.png"
      return "Pichu"
    when "20.png"
      return "Pikachu"
    when "21.png"
      return "Roy"
    when "22.png"
      return "Samus"
    when "23.png"
      return "Sheik"
    when "24.png"
      return "Yoshi"
    when "25.png"
      return "Young Link"
    when "26.png"
      return "Zelda"
    else
      return "null"
    end
  end
end
